name: '【auto】Trigger git tag'

on:
  workflow_run:
    workflows: ["【auto】Create git tag"]
    types: ["completed"]

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --abbrev=0 --tags)
          echo "Latest Tag: $latest_tag"
          echo "::set-output name=latest_tag::$latest_tag"
        
      - name: Build and push excite-emininal-api Amazon ECR
        run: |
          echo "実行！！"
          pwd
