name: '【auto】Trigger git tag'

on:
  push:
  workflow_run:
    workflows: ["【auto】Create git tag"]
    types: ["completed"]

jobs:
  release:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get Latest Tag
        id: get-latest-tag
        run: |
          git fetch --unshallow > /dev/null 2>&1
          TAG=$(git describe --tags --abbrev=0)
          echo "value=${TAG}" >> $GITHUB_OUTPUT
      
      - name: Get Latest Tag
        run: |
          echo "${{ steps.get-latest-tag.outputs.value }}"
