name: '【auto】Trigger git tag'

on:
  push:
  workflow_run:
    workflows: ["【auto】Create git tag"]
    types: ["completed"]

jobs:
  release:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get Latest Tag
        run: |
          git fetch --tags --prune > /dev/null 2>&1
          tag_list=$(git tag --list)

          # タグを改行文字で分割して配列に格納
          IFS=$'\n' read -rd '' -a tags <<< "$tag_list"

          # 配列から最後のタグを取得
          last_tag=${tags[-1]}

          # 最後のタグを出力
          echo "最後のタグ: $last_tag"
          echo "::set-output name=last_tag::$last_tag"
        
      - name: Build and push excite-emininal-api Amazon ECR
        run: |
          echo "実行！！"
          pwd
